### ISSUE TITLE
add recommended config

### ISSUE THREAD

**Issue by Uzlopak** [lirantal/eslint-plugin-anti-trojan-source#2]
Please add a recommended config. 

I am thinking of integrating your eslint plugin into my projects. When I see that somebody published a new version of an eslint-plugin by hovering in vscode over the corresponding line in my package.json then I want just upgrade the package and know that if a rule was added that it is already covered by the "recommended"-config and so i dont have to touch the .eslintrc file also. 

Currently I would need to check the new version if there is a useful new rule added and add it manually to my project, instead of being immediatly secured by the new rule.

Thank you for your work.

**Comment by lirantal** [comment]
That's a good idea. Would you like to contribute that to this project? I'm happy to merge your pull request.

**Comment by Uzlopak** [comment]
TBH: When I created this issue, I first checked if I could provide a PR, but I didnt find any simple example on how to add a config to a plugin. Googling for eslint plugin configuration does not give a simple solution. And checking other bigger plugins for sample code didnt help as it was always overcomplicated. So I have to decline unfortunately. :(

**Comment by lirantal** [comment]
There's a bit on that here https://eslint.org/docs/6.0.0/user-guide/configuring#using-eslintrecommended and also here https://www.freecodecamp.org/news/creating-your-own-eslint-config-package/ incase you wanted to give it a try still :)
